### ISSUE TITLE
[Issue]: compilation failure with gcc-15: ‘uint64_t’ does not name a type

### ISSUE THREAD

**Issue by AngryLoki** [RadeonOpenCompute/rocm_smi_lib#191]
### Problem Description

(somewhat similar to https://github.com/ROCm/ROCR-Runtime/issues/227)

Hi, as reported in https://bugs.gentoo.org/938112, gcc-15 was able to unscrable some headers, and now rocm_smi_lib build fails with:
```
In file included from /var/tmp/portage/dev-util/rocm-smi-6.1.1/work/rocm_smi_lib-rocm-6.1.1/include/rocm_smi/rocm_smi_gpu_metrics.h:47,
                 from /var/tmp/portage/dev-util/rocm-smi-6.1.1/work/rocm_smi_lib-rocm-6.1.1/src/rocm_smi_gpu_metrics.cc:44:
/var/tmp/portage/dev-util/rocm-smi-6.1.1/work/rocm_smi_lib-rocm-6.1.1/include/rocm_smi/rocm_smi_common.h:149:5: error: ‘uintptr_t’ does not name a type
  149 |     uintptr_t func_id_iter;
      |     ^~~~~~~~~
/var/tmp/portage/dev-util/rocm-smi-6.1.1/work/rocm_smi_lib-rocm-6.1.1/include/rocm_smi/rocm_smi_common.h:53:1: note: ‘uintptr_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   52 | #include <unordered_set>
  +++ |+#include <cstdint>
   53 |
```

Could you add `#include <cstdint>` to https://github.com/ROCm/rocm_smi_lib/blob/rocm-6.2.0/include/rocm_smi/rocm_smi_common.h? That's the only change needed for gcc-15. Thanks!

### Operating System

Gentoo

### CPU

-

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.2.0

### ROCm Component

rocm_smi_lib

**Comment by harkgill-amd** [comment]
Hi @AngryLoki, how are you installing gcc-15 prior to building rocm_smi_lib?

**Comment by AngryLoki** [comment]
@harkgill-amd , `emerge -va sys-devel/gcc:15 --autounmask-continue --autounmask-write && eselect gcc set x86_64-pc-linux-gnu-15`. But it OS/installation method makes no difference, GCC 15 will reach every distro eventually.

Here is a link with minimal reproduction: https://godbolt.org/z/dqGbnG8bY . This is not an issue of GCC (due to standard).

I'll add a PR, maybe it helps anybody.

**Comment by harkgill-amd** [comment]
After finally getting gcc-15 installed and working on Ubuntu 24.04, I was able to reproduce the issue and confirm your fix resolves it. Thanks for the PR, I'll confirm with the team if they would like to go forward and merge it or push the changes internally for simplicity.
